{% set name = "glidertools" %}
{% set version = " 2023.7.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07efc6d3e54eb78534b1eaace60a67b94abee145217ff73b3123ffd80f888176

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pytest-runner
    - setuptools_scm
  run:
    - python >=3.8
    - numexpr
    - netcdf4 
    - scikit-learn >=0.22
    - tqdm >=4
    - xarray >=2022.10.0
    - matplotlib-base
    - scipy
    - pandas
    - gsw

test:
  imports:
    - glidertools

about:
  home: https://github.com/GliderToolsCommunity/GliderTools
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'A toolkit for processing Seaglider base station NetCDF files: despiking, smoothing, outlier detection, backscatter, fluorescence quenching, calibration, gridding, interpolation.'

  description: |
    Glider tools is a Python 3.8+ package designed to process data from the first level of processing to a science ready dataset (delayed mode quality control). The package is designed to easily import data to a standard column format (numpy.ndarray or pandas.DataFrame). Cleaning and smoothing functions are flexible and can be applied as required by the user. We provide examples and demonstrate best practices as developed by the SOCCO Group, with early contributions from Polar Gliders at the University of Gothenburg. GliderTools includes contributions from VOTO. We aim to implement Best Practices developed by OceanGliders in the ongoing discussions.
  dev_url: https://github.com/GliderToolsCommunity/GliderTools

extra:
  recipe-maintainers:
    - jbusecke
    - callumrollo
